<?php
/**
 * ServicesVersionApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Version
 *
 * A Version represents a specific instance of the configuration for a service. A Version can be cloned, locked, activated, or deactivated.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServicesVersionApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicesVersionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateServiceVersion
     *
     * Activate a service version.
     *
     */
    public function testActivateServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cloneServiceVersion
     *
     * Clone a service version.
     *
     */
    public function testCloneServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createServiceVersion
     *
     * Create a service version.
     *
     */
    public function testCreateServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deactivateServiceVersion
     *
     * Deactivate a service version.
     *
     */
    public function testDeactivateServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServiceVersion
     *
     * Get a version of a service.
     *
     */
    public function testGetServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listServiceVersions
     *
     * List versions of a service.
     *
     */
    public function testListServiceVersions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for lockServiceVersion
     *
     * Lock a service version.
     *
     */
    public function testLockServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateServiceVersion
     *
     * Update a service version.
     *
     */
    public function testUpdateServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateServiceVersion
     *
     * Validate a service version.
     *
     */
    public function testValidateServiceVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
